### ISSUE TITLE
Errore con le dipendenze

### ISSUE THREAD

**Issue by giorginogreg** [dottorblaster/k8s-spiegato-a-mia-zia#1]
Ciao!
Ero incuriosito di vedere questa tua repo, stavo guardando un video in cui sei apparso, della gilda dei dev o una cosa del genere, e mi aveva incuriosito questo tuo progetto.

Stavo provando a far partire tutto ma sembra che ci sia un'errore di dipendenze, sopratutto con Vite (dipendenza di slidev).
Ho tentato di smanettare un pò con le versioni ma non ci sono riuscito.
Potrebbe essere relazionato a [questa issue](https://github.com/vitejs/vite/issues/6491), fammi sapere se riesci a workaround-are in qualche modo, e come.

Ti ringrazio e mille complimenti, sei un grande! 😁

**Comment by dottorblaster** [comment]
Ciao a te! Grazie per i complimenti :sweat_smile: 

Ho provato in locale e qui ancora parte tutto, che versione di Node stai usando? Qui con la `17.3.0` funziona

**Comment by dottorblaster** [comment]
(Comunque, queste sono solo le slide del talk: il manifest YAML lo trovi dentro la directory `manifests`, e per quello devi solo fare `kubectl apply`)

**Comment by giorginogreg** [comment]
Ciao, purtroppo sono stato un pò incasinato e vedo la issue nuovamente solo ora. Effettivamente avevo node alla versione 17.0.x, avendolo aggiornato all'ultima sono riuscito a far partire il tutto.
Non so se hai una registrazione del talk? Perchè ho visto le slide e ovviamente sono chiaramente un reminder per un talk..
Fammi sapere, grazie! 😁

**Comment by dottorblaster** [comment]
@giorginogreg qui trovi più informazioni https://talks.codemotion.com/kubernetes-spiegato-a-mia-zia-

**Comment by giorginogreg** [comment]
Esattamente ciò che cercavo.

Ancora grazie mille, mi hai fatto scoprire un’altra bellissima piattaforma 😍
